name: Update Streamlit App

on:
  push:
    branches:
      - main  # 监听主分支的代码推送

jobs:
  update_app:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Streamlit App
        run: |
          curl -X GET https://neckv2.streamlit.app/
